### ISSUE TITLE
PyTorch 0.4.0 problem

### ISSUE THREAD

**Issue by nerox8664** [osmr/imgclsmob#4]
The PResNet18 model seems incompatible with PyTorch 0.4.0.

```
Traceback (most recent call last):
  File "convert.py", line 135, in <module>
    net = ptcv_get_model("PreResNet18", pretrained=True)
  File "/home/nero/Files/Workspace/env/lib/python3.6/site-packages/pytorchcv/model_provider.py", line 190, in get_model
    net = _models[name](**kwargs)
  File "/home/nero/Files/Workspace/env/lib/python3.6/site-packages/pytorchcv/models/preresnet.py", line 582, in preresnet18
    return get_preresnet(blocks=18, model_name="preresnet18", **kwargs)
  File "/home/nero/Files/Workspace/env/lib/python3.6/site-packages/pytorchcv/models/preresnet.py", line 461, in get_preresnet
    local_model_store_dir_path=root)))
  File "/home/nero/Files/Workspace/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PreResNet:
	Unexpected key(s) in state_dict: "features.init_block.bn.num_batches_tracked", "features.stage1.unit1.body.conv1.bn.num_batches_tracked", "features.stage1.unit1.body.conv2.bn.num_batches_tracked", "features.stage1.unit2.body.conv1.bn.num_batches_tracked", "features.stage1.unit2.body.conv2.bn.num_batches_tracked", "features.stage2.unit1.body.conv1.bn.num_batches_tracked", "features.stage2.unit1.body.conv2.bn.num_batches_tracked", "features.stage2.unit2.body.conv1.bn.num_batches_tracked", "features.stage2.unit2.body.conv2.bn.num_batches_tracked", "features.stage3.unit1.body.conv1.bn.num_batches_tracked", "features.stage3.unit1.body.conv2.bn.num_batches_tracked", "features.stage3.unit2.body.conv1.bn.num_batches_tracked", "features.stage3.unit2.body.conv2.bn.num_batches_tracked", "features.stage4.unit1.body.conv1.bn.num_batches_tracked", "features.stage4.unit1.body.conv2.bn.num_batches_tracked", "features.stage4.unit2.body.conv1.bn.num_batches_tracked", "features.stage4.unit2.body.conv2.bn.num_batches_tracked", "features.post_activ.bn.num_batches_tracked"
```

**Comment by osmr** [comment]
Thanks, I've added backward compatibility with PyTorch 0.4.0.
