### ISSUE TITLE
'RefVariable' object has no attribute 'bind'

### ISSUE THREAD

**Issue by jttqbc666** [osmr/imgclsmob#57]
Traceback (most recent call last):

  File "<ipython-input-1-02e4590da3d4>", line 1, in <module>
    runfile('D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master/convert_models.py', args='--src-fwk=gluon --dst-fwk=keras --src-model=resnet18 --dst-model=resnet18 --src-params=../imgclsmob_data/gl-resnet18-0951/resnet18-0951-98a2545b.params --dst-params=../imgclsmob_data/gl-resnet18-0951/resnet18.h5 --save-dir=../imgclsmob_data/gl-resnet18-0951/', wdir='D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master')

  File "D:\ruanjian\anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\ruanjian\anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master/convert_models.py", line 1458, in <module>
    main()

  File "D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master/convert_models.py", line 1398, in main
    src_param_keys=src_param_keys)

  File "D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master/convert_models.py", line 745, in convert_gl2ke
    process_width(src_key, dst_key, src_weight)

  File "D:/Artificial_Intelligence/anaconda_spyder/imgclsmob-master/convert_models.py", line 726, in process_width
    dst_weight.bind(mx.nd.array(src_weight))

AttributeError: 'RefVariable' object has no attribute 'bind'

**Comment by osmr** [comment]
The callstack is not enough, I need at least the contents of the log-file (`../imgclsmob_data/gl-resnet18-0951/train.log`) and the `keras.json` file.
