### ISSUE TITLE
questions while a experimental train

### ISSUE THREAD

**Issue by JayFu** [osmr/imgclsmob#61]
Hi Thanks for such a brilliant work.

i was going to train a ghost net model on tf2 by train_tf2.py. And i used a tiny dataset at first which contains 78 images in training set and 40 for val and set epoch as 1, batch size as 4.
But it seem cannot stop this single epoch. Let me show you in the code.
I put some print and counter into the loop, like.

   ```
 print(train_img_count)
    num_epochs = args.num_epochs
    print(num_epochs)
    for epoch in range(num_epochs):
        print(20) #meanless thing
        conuter= 0
        for images, labels in train_data:
            print(conuter)
            conuter+=1
            train_step(images, labels)
        print(16) #meanless thing
```
In this case, the terminal keep printing out the **_counter_** . Although it didn't throw any errors or excepts, it just keep runing. The counter is much bigger than the number of train images(300 vs 78).
The terminal output going like

```
Found 78 images belonging to 2 classes.
Found 40 images belonging to 2 classes.
78             # train_img_count
1               # num_epochs
20            # that meanless number
0               #counter started from here
1
2
3
4
5
6
.......
300
```
Any idea about this?

**Comment by osmr** [comment]
Don't use `train_tf2.py` as an example, this script is still not properly debugged. IMHO, specifically, your problem is related to the features of TF2's `Dataset`. You have to manually terminate epoch cycle (see `eval_tf2.py` script).

**Comment by JayFu** [comment]
@osmr  Thanks! I am trying to terminate it.

**Comment by JayFu** [comment]
@osmr Hi, I turned to torch and training part finished.
But while I want to eval the model it says that there are missing keys in state_dict and with hug quantity of keys name.
I didn't modify code and just put dataset there and train by the command line
```
train_pt.py --model ghostnet --dataset ImageNet1K --work-dir imgclsmob_data/ --num-epochs 5 --num-gpus 2 --batch-size 256 --num-classes 336 --optimizer-name sgd --lr 0.005 --save-interval 1 --save-dir ./
```
and eval by 
```
python eval_pt.py --model ghostnet --work-dir ./imgclsmob_data/ --resume ./imagenet_ghostnet_last_0001_0.9931.states 
```

The command reports (I use .... to skip similar keys name) 
```
Traceback (most recent call last):
  File "eval_pt.py", line 450, in <module>
    main()
  File "eval_pt.py", line 446, in main
    test_model(args=args)
  File "eval_pt.py", line 376, in test_model
    remove_module=args.remove_module)
  File "/media/e/hujiang/imgclsmob/pytorch/utils.py", line 115, in prepare_model
    net.load_state_dict(checkpoint)
  File "/media/e/hujiang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GhostNet:
	Missing key(s) in state_dict: "features.init_block.conv.weight", "features.init_block.bn.weight", "features.init_block.bn.bias", "features.init_block.bn.running_mean", "features.init_block.bn.running_var",

....
....
....
 "features.final_block.bn.running_mean", "features.final_block.bn.running_var", "output.conv1.conv.weight", "output.conv1.bn.weight", "output.conv1.bn.bias", "output.conv1.bn.running_mean", "output.conv1.bn.running_var", "output.conv2.weight", "output.conv2.bias". 
	Unexpected key(s) in state_dict: "module.features.init_block.conv.weight", "module.features.init_block.bn.weight", "module.features.init_block.bn.bias", "module.features.init_block.bn.running_mean", "module.features.init_block.bn.running_var",
....
....
....
"module.features.final_block.bn.running_mean", "module.features.final_block.bn.running_var", "module.features.final_block.bn.num_batches_tracked", "module.output.conv1.conv.weight", "module.output.conv1.bn.weight", "module.output.conv1.bn.bias", "module.output.conv1.bn.running_mean", "module.output.conv1.bn.running_var", "module.output.conv1.bn.num_batches_tracked", "module.output.conv2.weight", "module.output.conv2.bias". 
```

**Comment by osmr** [comment]
Try to use a `.pth` file instead of `.states` during inference.

**Comment by JayFu** [comment]
Sorry for I didn't clarify that I tried both but end with the same.

**Comment by osmr** [comment]
OK. Try to run `eval_pt.py` with an additional parameter `--remove-module`.
