### ISSUE TITLE
Transfer learning on ICNet with different number of classes and image size with Tensorflow 2

### ISSUE THREAD

**Issue by hetfmt** [osmr/imgclsmob#74]
Hi,
Thank you for a great project - which I am however struggling to use the way I would like :-)

I would like to use the already trained ICNet model in Tensorflow 2 to perform transfer learning for semantic segmentation.

First of all: What is the correct way of changing the default (pre-trained) input image size? 
I have tried the following but it produces an error ("Dimensions of inputs should match..."):
`
from tf2cv.model_provider import get_model
import tensorflow as tf
net = get_model("icnet_resnetd50b_cityscapes", pretrained=True, classes=1)
net.in_size = (600, 700)  # Change input image size - default is (480, 480)
x = tf.random.normal((1, 600, 700, 3))
y = net(x)
`

Secondly, I would like to re-train only the "head" of the model, since I have a limited number of images. Assuming that the issue with the image size has been solved, will the following change allow only the "head" of the model to be re-trained?
`
net.trainable = False  # Change entire network to "not trainable"
net.final_block.trainable = True  # Make "head" trainable
`
Or is it more complicated than that?
Thanks.

**Comment by hetfmt** [comment]
Hi again,

I just realized that I can pass "in_size" in the "get_model" call such that e.g:

`in_size = (512, 1024)`
`net = get_model("icnet_resnetd50b_cityscapes", pretrained=True, classes=1, in_size=in_size)`
`x = tf.random.normal((1, in_size[0], in_size[1], 3))`
`y = net(x)`

appears to be working. I also noticed that there are a number of requirements to the "in_size" that must be satisfied, but apart from the following warning it appears to be working:

`WARNING:tensorflow:Skipping loading of weights for layer final_block due to mismatch in shape ((1, 1, 128, 1) vs (1, 1, 128, 19)).`

However, when I continue with the script, it throws an error:
[icnet_test.txt](https://github.com/osmr/imgclsmob/files/5074852/icnet_test.txt)


_[INFO] loading images...
[INFO] 324 images loaded...
2020-08-14 13:31:22.165785: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-08-14 13:31:22.192731: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3693115000 Hz
2020-08-14 13:31:22.196158: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55df5eed83d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-14 13:31:22.196182: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-14 13:31:22.196271: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING:tensorflow:Skipping loading of weights for layer final_block due to mismatch in shape ((1, 1, 128, 1) vs (1, 1, 128, 19)).
WARNING:tensorflow:Skipping loading of weights for layer final_block due to mismatch in shape ((1, 1, 128, 1) vs (1, 1, 128, 19)).
WARNING:tensorflow:Skipping loading of weights for layer final_block due to mismatch in shape ((1, 1, 128, 1) vs (1, 1, 128, 19)).
[INFO] compiling model...
[INFO] summary for base model...
Model: "ic_net"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
branch1 (ICInitBlock)        multiple                  29024     
_________________________________________________________________
branch2 (MultiOutputSequenti multiple                  46896320  
_________________________________________________________________
conv_y2 (ConvBlock)          multiple                  132096    
_________________________________________________________________
final_block (ICHeadBlock)    multiple                  485760    
=================================================================
Total params: 47,543,200
Trainable params: 0
Non-trainable params: 47,543,200
_________________________________________________________________
None
[INFO] training head...
Epoch 1/100
Traceback (most recent call last):
  File "/home/autofom/Henrik/Programming/Segmentation/ICNet/network.py", line 146, in <module>
    epochs=args["epochs"])
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tf2cv/models/icnet.py:329 call  *
        y3, y2 = self.branch2(x, training=training)
    /home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tf2cv/models/common.py:2433 call  *
        x = block(x, **kwargs)
    /home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tf2cv/models/common.py:2497 call  *
        out_size = self.calc_out_size(x)
    /home/autofom/anaconda3/envs/tf2/lib/python3.6/site-packages/tf2cv/models/common.py:2515 calc_out_size  *
        return tuple(s // self.scale_factor for s in in_size)

    TypeError: unsupported operand type(s) for //: 'NoneType' and 'int'

If I add a "print(in_shape)" in the "calc_out_size" function in "common.py", it prints: [None, None]
so after all, something is not right? Any help is most appreciated.
Thanks.

**Comment by osmr** [comment]
The `get_model` function with the `pretrained=True` does not contain any code to analyze if the parameters of the current model do not match the parameters of the trained model. You must do this yourself.
