### ISSUE TITLE
ValueError: Input 0 is incompatible with layer features/stage1/unit1/body/conv2/conv/convgroup1: expected ndim=4, found ndim=0

### ISSUE THREAD

**Issue by luogen1996** [osmr/imgclsmob#8]
> 
Traceback (most recent call last):
  File "C:/Users/THINKPAD/Desktop/kaggle_code/quickdraw-doodle-recognition/baseline/kerascv_test.py", line 4, in <module>
    net=get_model("resnext101_32x4d",pretrained=True)
  File "D:\python3.6\lib\site-packages\kerascv\model_provider.py", line 172, in get_model
    net = _models[name](**kwargs)
  File "D:\python3.6\lib\site-packages\kerascv\models\resnext.py", line 487, in resnext101_32x4d
    return get_resnext(blocks=101, cardinality=32, bottleneck_width=4, model_name="resnext101_32x4d", **kwargs)
  File "D:\python3.6\lib\site-packages\kerascv\models\resnext.py", line 446, in get_resnext
    **kwargs)
  File "D:\python3.6\lib\site-packages\kerascv\models\resnext.py", line 380, in resnext
    name="features/stage{}/unit{}".format(i + 1, j + 1))
  File "D:\python3.6\lib\site-packages\kerascv\models\resnext.py", line 273, in resnext_unit
    name=name + "/body")
  File "D:\python3.6\lib\site-packages\kerascv\models\resnext.py", line 208, in resnext_bottleneck
    name=name + "/conv2")
  File "D:\python3.6\lib\site-packages\kerascv\models\resnext.py", line 155, in resnext_conv3x3
    name=name)
  File "D:\python3.6\lib\site-packages\kerascv\models\resnext.py", line 66, in resnext_conv
    name=name + "/conv")
  File "D:\python3.6\lib\site-packages\kerascv\models\common.py", line 109, in conv2d
    name=name + "/convgroup{}".format(gi + 1))(xi)
  File "D:\python3.6\lib\site-packages\keras\engine\base_layer.py", line 414, in __call__
    self.assert_input_compatibility(inputs)
  File "D:\python3.6\lib\site-packages\keras\engine\base_layer.py", line 311, in assert_input_compatibility
    str(K.ndim(x)))
ValueError: Input 0 is incompatible with layer features/stage1/unit1/body/conv2/conv/convgroup1: expected ndim=4, found ndim=0
> 
there are some problems when i try to use 'ResNeXt' . What's wrong with it?

**Comment by osmr** [comment]
This traceback only shows that the problem is in a group convolution. Do other networks work for you? Does the example script from the README work fine in your case?
